name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: |
          zig build test
          zig build -Dtarget=x86-windows-gnu test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
        # Note that there's no testing for 32-bit on macos since offical support has been dropped
      - run: |
          zig build test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: |
          zig build test
          zig build -Dtarget=x86-linux-gnu test
