name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          zig build test
          zig build -Dtarget=x86-windows-gnu test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          zig build test
          zig build -Dtarget=x86-macos-gnu test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: |
          zig build test
          zig build -Dtarget=x86-linux-gnu test
